version: '3'

services:
  node-backend:
    build: .
    image: node-backend
    env_file:
      - .env.dev
    ports:
      - '3000:3000'
    depends_on:
      - mysql
    networks:
      - node-network

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - node-network
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - node-network

volumes:
  db-data:

networks:
  node-network:
    driver: bridge
